// ignore: dangling_library_doc_comments
/// Flutter icons AppIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
///
///

import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String _kFontPkg = 'app_ui';

  static const IconData accountFill =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accountOutline =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archive = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backArrow = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bold = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buletyPoint =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkboxFilled =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contactsFill =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contactsOutline =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contacts = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drag = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropdown = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData editProfile =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exportIcon =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyeClose = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyeOpen = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData funnel = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeFill = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeOutline =
      IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData italic = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData media = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData multipleSelection =
      IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationFill =
      IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationOutline =
      IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification =
      IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData privacyPolicy =
      IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quickReply =
      IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radioDefault =
      IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radioSelected =
      IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redo = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reminders = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rightArrow =
      IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData syncIcon = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData termsOfUse =
      IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unarchive = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData underline = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wipeAccount =
      IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
